name: prod release
on:
  release:
    types: [published]

permissions:
  contents: "read"
  id-token: "write"

#Based on https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
#and https://cloud.google.com/blog/products/devops-sre/using-github-actions-with-google-cloud-deploy

jobs:
  test:
    name: Test, build and publish
    runs-on:
      group: "Cabana-CICD"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Optional, use if you use setuptools_scm
          submodules: true # Optional, use if you have submodules

      - uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Test with tox
        run: |
          poetry install --no-interaction
          poetry run tox

      - name: Build
        run: pipx run build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
