name: prod release
on:
  push
  #release:
  #  types: [published]

permissions:
  contents: "read"
  id-token: "write"

#Based on https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
#and https://cloud.google.com/blog/products/devops-sre/using-github-actions-with-google-cloud-deploy

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Optional, use if you use setuptools_scm
          submodules: true # Optional, use if you have submodules

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels:
    runs-on:
      group: "Cabana-CICD"
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
